### ISSUE TITLE
Can't easily select code in code blocks when viewed in browser

### ISSUE THREAD

**Issue by aseagram** [BAAQMD/charting-annual-data#1]
When viewed in a browser, it is nearly impossible to select parts of the code blocks (with mouse, with the goal of copy+paste) with a standard mouse. Perhaps line-endings have something to do with it?

See example demonstration of trying to select part of the code block with a mouse.

![highlight](https://user-images.githubusercontent.com/4453177/78397205-b54d0a00-75a5-11ea-8eb8-2c7a1b46d7cf.gif)

Tested with Google Chrome 80.0.3987.149 (Official Build) (64-bit)

**Comment by dholstius** [comment]
This seems like it could be an issue experienced by other [bookdown](https://bookdown.org) users. 

@arihusain : Can you replicate this? If so, could you do some quick Googling?

**Comment by arihusain** [comment]
Could not find a perfect solution, but quickest fix is to use the copy icon in the upper right hand corner of the code snippet and edit from there. Will continue looking in free time for better solution.
<img width="591" alt="Copy-Paste-Bookdown" src="https://user-images.githubusercontent.com/63366012/78823097-fcb20c80-7990-11ea-8c1a-651d3451e283.png">
 

@holstius @aseagram

**Comment by aseagram** [comment]
Hm, good point. That's still not the most convenient (re: wanting just a line of two of the snippet), but works.

This isn't the case for viewing the raw HTML file hosted internally though; I may have been looking at that instead, which doesn't have the copy button.

**Comment by dholstius** [comment]
Can reproduce:
- on Chrome (80.0.3987.163, OS X)
- on [a different page](https://baaqmd.github.io/charting-annual-data/03-emissions.html) of the same GitBook
- on the `bookdown` [author's example GitBook](https://bookdown.org/yihui/bookdown/latex.html)

But, oddly, **things work just fine on Safari** (13.0.4, OS X).

Filing this issue at the [bookdown repo](https://github.com/rstudio/bookdown) is warranted, I think, by the fact that it reproduces on the author's own examples. @aseagram do you have time to do this?

**Comment by aseagram** [comment]
Filed rstudio/bookdown#874 ; from my (novice) perspective, looks like some squirrely HTML/CSS combinations.

We'll see what happens here, but in the mean time, you can inspect element > uncheck `pointer-events: none`...!

**Comment by aseagram** [comment]
@holstius see: https://github.com/rstudio/bookdown/issues/874#issuecomment-614943327
Maybe check what version of `pandoc` is on the server

**Comment by aseagram** [comment]
@dholstius see: https://github.com/rstudio/bookdown/issues/874#issuecomment-624870311
can this be updated now on our server?

**Comment by dholstius** [comment]
`pandoc` 2.9 now installed on RStudio server via:

```
cd ~
wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
```

... following [instructions at the official Pandoc site](https://pandoc.org/installing.html#all-platforms). Verified with:

```
which pandoc
/usr/bin/pandoc --version
```

@aseagram Rebuild of gitbook seems good. I can select arbitrary lines in the same code chunk you posted a `.gif` of at the top of this issue. How does it look to you?

**Comment by aseagram** [comment]
It works! Excellent. Thanks for updating the server.
